version: '3.8'

services:
  db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev_db
    volumes:
      - koden_postgres_data:/var/lib/postgresql/data
    command: >
      bash -c "
        rm -rf /var/lib/apt/lists/* &&
        apt-get clean &&
        /usr/local/bin/docker-entrypoint.sh postgres
      "
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - koden_redis_data:/data

volumes:
  koden_postgres_data:
  koden_redis_data: