"""Update user table to include firebase uid

Revision ID: 9a2026e724bc
Revises: 1aa8d852db01
Create Date: 2025-06-07 19:23:39.196322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9a2026e724bc'
down_revision: Union[str, None] = '1aa8d852db01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firebase_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_user_firebase_uid'), 'user', ['firebase_uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_firebase_uid'), table_name='user')
    op.drop_column('user', 'firebase_uid')
    # ### end Alembic commands ###
